name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
            packages: scheme-basic

      - name: Check `tlmgr` version
        run: tlmgr --version

      - name: Install Biber
        run: tlmgr install biber

      - name: LaTeX compilation
        run: |
         cd document
         latexmk -f
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            document/Thesis.pdf  # Update with the actual path to your built PDF
          token: ${{ secrets.GITHUB_TOKEN }}
